# -*- coding: utf-8 -*-
"""H1 - emotion followers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPBFtCJESC2d4S6Jbbreln-afQoB7_TO
"""

import pandas as pd
df = pd.read_csv("tweets_with_scores.csv")

df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.floor("D")# переделать в текст и оставить только день (без ч и мин), coerce - правка кривых данных

daily = (
    df
    .sort_values("date")
    .groupby("date", as_index=False) # группа с однинаковой датой
    .agg(
        followers_count=("followers_count", "last"), # ласт чисоо подписчиков за день
        emotion_score=("TweetEmotionScore", "mean") # среднее по эмоц коэфу за день
    )
)

daily["followers_change"] = daily["followers_count"].diff() # изменение подписок по дням
daily["emotion_change"] = daily["emotion_score"].diff()

daily = daily.sort_values("date").dropna() # дроп пустых значений

daily.head()

corr = daily[["emotion_change", "followers_change"]].corr(method="spearman")
corr # корреляция

import matplotlib.pyplot as plt

plt.figure(figsize=(7, 5))
plt.scatter(
    daily["emotion_change"],
    daily["followers_change"],
    alpha=0.4
)

plt.axhline(0) # горизонт линия (рост\спад подписок)
plt.axvline(0) # верт линия (рост\спад эмоций)

plt.xlabel("Изменение эмоционального коэффициента")
plt.ylabel("Изменение числа подписчиков")
plt.title("Связь изменений эмоций и подписчиков")

plt.grid(alpha=0.3)
plt.show()

import seaborn as sns

plt.figure(figsize=(4.5, 4))
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True
)
plt.title("Корреляция изменений эмоций и подписчиков")
plt.show()